"""empty message

Revision ID: 13e0c7ba877b
Revises: a8931ed58697
Create Date: 2026-05-11 02:42:49.267297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e0c7ba877b'
down_revision = 'a8931ed58697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
